# Generated by Django 6.0.1 on 2026-02-20 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Persona'), ('COMPANY', 'Azienda'), ('HYBRID', 'Persona + Attivita')], default='PERSON', max_length=10)),
                ('person_name', models.CharField(blank=True, max_length=160)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('role_customer', models.BooleanField(default=False)),
                ('role_supplier', models.BooleanField(default=False)),
                ('role_payee', models.BooleanField(default=False)),
                ('role_income_source', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'display_name'], name='contacts_co_owner_i_fd0ff7_idx'), models.Index(fields=['owner', 'is_active'], name='contacts_co_owner_i_4a3fbe_idx'), models.Index(fields=['owner', 'role_customer'], name='contacts_co_owner_i_96b37c_idx'), models.Index(fields=['owner', 'role_supplier'], name='contacts_co_owner_i_5fd1f5_idx'), models.Index(fields=['owner', 'role_payee'], name='contacts_co_owner_i_d2846f_idx'), models.Index(fields=['owner', 'role_income_source'], name='contacts_co_owner_i_695f1b_idx')],
                'unique_together': {('owner', 'display_name')},
            },
        ),
    ]
