# Generated by Django 6.0.1 on 2026-02-27 18:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactToolbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox', to='contacts.contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('currency_code', models.CharField(default='EUR', max_length=3)),
                ('pricing_notes', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='contacts.contacttoolbox')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_order', models.PositiveSmallIntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contacts.contactpricelist')),
            ],
            options={
                'ordering': ['row_order', 'id'],
                'indexes': [
                    models.Index(fields=['owner', 'price_list', 'row_order'], name='contacts_co_owner_i_2f9eeb_idx'),
                    models.Index(fields=['owner', 'price_list', 'is_active'], name='contacts_co_owner_i_9f827f_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='contacttoolbox',
            index=models.Index(fields=['owner', 'contact'], name='contacts_co_owner_i_5bb251_idx'),
        ),
        migrations.AddIndex(
            model_name='contactpricelist',
            index=models.Index(fields=['owner', 'toolbox', 'is_active'], name='contacts_co_owner_i_80549c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactpricelist',
            index=models.Index(fields=['owner', 'toolbox', 'updated_at'], name='contacts_co_owner_i_9470c5_idx'),
        ),
    ]
