# Generated by Django 6.0.1 on 2026-02-27 20:15

from django.db import DatabaseError, migrations, models


def _table_columns(schema_editor, table_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    return {col.name for col in description}


def _table_constraints(schema_editor, table_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return connection.introspection.get_constraints(cursor, table_name)


def _add_column_if_missing(schema_editor, table_name, column_name, sql_type, default_sql=None):
    columns = _table_columns(schema_editor, table_name)
    if column_name in columns:
        return

    table_q = schema_editor.quote_name(table_name)
    column_q = schema_editor.quote_name(column_name)
    default_clause = f" DEFAULT {default_sql}" if default_sql is not None else ""
    schema_editor.execute(f"ALTER TABLE {table_q} ADD COLUMN {column_q} {sql_type}{default_clause}")


def _drop_column_if_exists(schema_editor, table_name, column_name):
    columns = _table_columns(schema_editor, table_name)
    if column_name not in columns:
        return

    table_q = schema_editor.quote_name(table_name)
    column_q = schema_editor.quote_name(column_name)
    try:
        schema_editor.execute(f"ALTER TABLE {table_q} DROP COLUMN {column_q}")
    except DatabaseError:
        # On older SQLite builds DROP COLUMN may be unavailable; keeping legacy columns is acceptable.
        if schema_editor.connection.vendor != "sqlite":
            raise


def _rename_column_if_needed(schema_editor, table_name, old_name, new_name):
    columns = _table_columns(schema_editor, table_name)
    if new_name in columns or old_name not in columns:
        return

    table_q = schema_editor.quote_name(table_name)
    old_q = schema_editor.quote_name(old_name)
    new_q = schema_editor.quote_name(new_name)
    schema_editor.execute(f"ALTER TABLE {table_q} RENAME COLUMN {old_q} TO {new_q}")


def forward_align_pricebook_schema(apps, schema_editor):
    price_list_table = "contacts_contactpricelist"
    item_table = "contacts_contactpricelistitem"

    _add_column_if_missing(schema_editor, price_list_table, "pricing_notes", "text NOT NULL", "''")
    for legacy_col in ("subtotal_net", "tax_amount", "total_amount", "vat_rate"):
        _drop_column_if_exists(schema_editor, price_list_table, legacy_col)

    _rename_column_if_needed(schema_editor, item_table, "quantity", "min_quantity")
    _rename_column_if_needed(schema_editor, item_table, "unit_price_net", "unit_price")

    _add_column_if_missing(schema_editor, item_table, "min_quantity", "numeric(10,2) NOT NULL", "1.00")
    _add_column_if_missing(schema_editor, item_table, "unit_price", "numeric(12,2) NOT NULL", "0.00")
    _add_column_if_missing(schema_editor, item_table, "max_quantity", "numeric(10,2)")
    _add_column_if_missing(schema_editor, item_table, "is_active", "boolean NOT NULL", "TRUE")

    for legacy_col in ("discount", "line_total_net", "quantity", "unit_price_net"):
        _drop_column_if_exists(schema_editor, item_table, legacy_col)

    constraints = _table_constraints(schema_editor, item_table)
    index_name = "contacts_co_owner_i_9f827f_idx"
    if index_name not in constraints:
        item_q = schema_editor.quote_name(item_table)
        idx_q = schema_editor.quote_name(index_name)
        schema_editor.execute(
            f"CREATE INDEX IF NOT EXISTS {idx_q} ON {item_q} (owner_id, price_list_id, is_active)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contacttoolbox_contactpricelist_contactpricelistitem_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forward_align_pricebook_schema, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="contactpricelist",
                    name="pricing_notes",
                    field=models.TextField(blank=True),
                ),
                migrations.RenameField(
                    model_name="contactpricelistitem",
                    old_name="quantity",
                    new_name="min_quantity",
                ),
                migrations.RenameField(
                    model_name="contactpricelistitem",
                    old_name="unit_price_net",
                    new_name="unit_price",
                ),
                migrations.AddField(
                    model_name="contactpricelistitem",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name="contactpricelistitem",
                    name="max_quantity",
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                migrations.RemoveField(
                    model_name="contactpricelist",
                    name="subtotal_net",
                ),
                migrations.RemoveField(
                    model_name="contactpricelist",
                    name="tax_amount",
                ),
                migrations.RemoveField(
                    model_name="contactpricelist",
                    name="total_amount",
                ),
                migrations.RemoveField(
                    model_name="contactpricelist",
                    name="vat_rate",
                ),
                migrations.RemoveField(
                    model_name="contactpricelistitem",
                    name="discount",
                ),
                migrations.RemoveField(
                    model_name="contactpricelistitem",
                    name="line_total_net",
                ),
                migrations.AddIndex(
                    model_name="contactpricelistitem",
                    index=models.Index(
                        fields=["owner", "price_list", "is_active"],
                        name="contacts_co_owner_i_9f827f_idx",
                    ),
                ),
            ],
        ),
    ]
