# Generated by Django 6.0.1 on 2026-02-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contactpricelist_subtotal_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='entity_type',
            field=models.CharField(choices=[('PERSON', 'Persona'), ('HYBRID', 'Persona + Attivita'), ('ENTITY', 'Ente'), ('COMPANY', 'Azienda')], default='PERSON', max_length=10),
        ),
    ]
