# Generated by Django 6.0.1 on 2026-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='contacts/profile_images/%Y/%m/'),
        ),
    ]
