# Generated by Django 6.0.1 on 2026-03-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_contact_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDeliveryAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                ("recipient_name", models.CharField(blank=True, max_length=160)),
                ("line1", models.CharField(max_length=180)),
                ("line2", models.CharField(blank=True, max_length=180)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(max_length=120)),
                ("province", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(default="Italia", max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_addresses",
                        to="contacts.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["row_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="contactdeliveryaddress",
            index=models.Index(
                fields=["owner", "contact", "is_active"],
                name="contacts_co_owner_i_cc9f86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactdeliveryaddress",
            index=models.Index(
                fields=["owner", "contact", "row_order"],
                name="contacts_co_owner_i_8f8d5f_idx",
            ),
        ),
    ]
