# Generated by Django 6.0.1 on 2026-04-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_profile_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactdeliveryaddress',
            new_name='contacts_co_owner_i_61eca8_idx',
            old_name='contacts_co_owner_i_cc9f86_idx',
        ),
        migrations.RenameIndex(
            model_name='contactdeliveryaddress',
            new_name='contacts_co_owner_i_3b834a_idx',
            old_name='contacts_co_owner_i_8f8d5f_idx',
        ),
    ]
