# Generated by Django 6.0.1 on 2026-02-19 20:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_project_hero_actions_config'),
        ('subscriptions', '0005_alter_currency_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('amount_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('SENT', 'Inviato'), ('APPROVED', 'Approvato'), ('REJECTED', 'Rifiutato'), ('EXPIRED', 'Scaduto')], default='DRAFT', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_quotes', to='projects.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_quotes', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('ISSUED', 'Emessa'), ('PAID', 'Pagata'), ('OVERDUE', 'Scaduta'), ('CANCELED', 'Annullata')], default='DRAFT', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices', to='subscriptions.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices', to='projects.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices', to='projects.project')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance_hub.quote')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aperto'), ('IN_PROGRESS', 'In corso'), ('WAITING', 'In attesa'), ('DONE', 'Completato'), ('CANCELED', 'Annullato')], default='OPEN', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_work_orders', to='subscriptions.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_work_orders', to='projects.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_work_orders', to='projects.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['owner', 'status'], name='finance_hub_owner_i_3082bb_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['owner', 'valid_until'], name='finance_hub_owner_i_b2359c_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('owner', 'code'), name='finance_quote_owner_code_unique_non_empty'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', 'status'], name='finance_hub_owner_i_58c1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', 'due_date'], name='finance_hub_owner_i_2b520a_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('owner', 'code'), name='finance_invoice_owner_code_unique_non_empty'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['owner', 'status'], name='finance_hub_owner_i_147120_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['owner', 'start_date'], name='finance_hub_owner_i_801922_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('owner', 'code'), name='finance_work_order_owner_code_unique_non_empty'),
        ),
    ]
