# Generated by Django 6.0.1 on 2026-02-20 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_hub', '0002_quoteline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rate', 'code'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='vat_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='finance_hub.vatcode'),
        ),
        migrations.AddIndex(
            model_name='vatcode',
            index=models.Index(fields=['owner', 'is_active'], name='finance_hub_owner_i_77ec3e_idx'),
        ),
        migrations.AddIndex(
            model_name='vatcode',
            index=models.Index(fields=['owner', 'rate'], name='finance_hub_owner_i_c91402_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vatcode',
            unique_together={('owner', 'code')},
        ),
    ]
