# Generated by Django 6.0.1 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_hub", "0003_vatcode_quote_vat_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="customer_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="customer_signed_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="customer_signed_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="quote",
            name="customer_signed_user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="quote",
            name="public_access_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="public_access_token",
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
    ]
