# Generated by Django 6.0.1 on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_contactdeliveryaddress"),
        ("finance_hub", "0004_quote_public_access_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_quotes",
                to="contacts.contactdeliveryaddress",
            ),
        ),
    ]
