# Generated by Django 6.0.1 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_hub", "0005_quote_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="customer_decision_note",
            field=models.TextField(blank=True),
        ),
    ]
