# Generated by Django 6.0.1 on 2026-03-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_hub", "0006_quote_customer_decision_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="finance_hub.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="finance_hub.shippingmethod",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["owner", "is_active"], name="fh_pm_owner_active_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["owner", "name"], name="fh_pm_owner_name_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(fields=["owner", "is_active"], name="fh_sm_owner_active_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(fields=["owner", "name"], name="fh_sm_owner_name_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("owner", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="shippingmethod",
            unique_together={("owner", "name")},
        ),
    ]
