# Generated by Django 6.0.1 on 2026-04-29 18:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_davcal_owner_i_f6be42_idx_core_davcal_owner_i_e922b1_idx_and_more'),
        ('finance_hub', '0011_migrate_subscriptions'),
        ('projects', '0012_rename_projects_sub_owner_i_774818_idx_projects_su_owner_i_785c2e_idx_and_more'),
        ('transactions', '0005_alter_transaction_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('BANK', 'Bank'), ('CARD', 'Card'), ('CASH', 'Cash'), ('INVEST', 'Investment'), ('OTHER', 'Other')], default='BANK', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_accounts',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('interval_unit', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='MONTH', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10)),
                ('autopay', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('PLANNED', 'Planned'), ('PAID', 'Paid'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PLANNED', max_length=10)),
            ],
        ),
        migrations.RenameIndex(
            model_name='incomesource',
            new_name='finance_hub_owner_i_f5f38f_idx',
            old_name='finance_hub_incomes_owner_i_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='finance_hub_owner_i_25bf49_idx',
            old_name='finance_hub_tag_owner_n_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_hub.currency'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_hub.currency'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_hub.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_hub.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices', to='finance_hub.account'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_work_orders', to='finance_hub.account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='finance_hub.account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='projects.category'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_hub.currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.payee'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='finance_hub.tag'),
        ),
        migrations.AddField(
            model_name='subscriptionoccurrence',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_hub.currency'),
        ),
        migrations.AddField(
            model_name='subscriptionoccurrence',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionoccurrence',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='finance_hub.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionoccurrence',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_occurrence', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'is_active'], name='core_accoun_owner_i_94d652_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'status', 'next_due_date'], name='finance_hub_owner_i_32795e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'project', 'status'], name='finance_hub_owner_i_76a38b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='subscriptionoccurrence',
            index=models.Index(fields=['owner', 'due_date', 'state'], name='finance_hub_owner_i_ac54ba_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionoccurrence',
            index=models.Index(fields=['owner', 'subscription', 'due_date'], name='finance_hub_owner_i_4a2da5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionoccurrence',
            unique_together={('subscription', 'due_date')},
        ),
    ]
