# Generated by Django 6.0.1 on 2026-02-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="routines", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["owner", "is_active"], name="routines_ro_owner__f6a1cd_idx")],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="RoutineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("weekday", models.PositiveSmallIntegerField(choices=[(0, "Lun"), (1, "Mar"), (2, "Mer"), (3, "Gio"), (4, "Ven"), (5, "Sab"), (6, "Dom")], default=0)),
                ("time", models.TimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="routineitems", to=settings.AUTH_USER_MODEL)),
                ("routine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="routines.routine")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner", "weekday"], name="routines_ro_owner__2b12d1_idx"),
                    models.Index(fields=["owner", "routine", "weekday"], name="routines_ro_owner__a1a4c0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutineCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_start", models.DateField()),
                ("status", models.CharField(choices=[("PLANNED", "Planned"), ("DONE", "Done"), ("SKIPPED", "Skipped")], default="PLANNED", max_length=10)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checks", to="routines.routineitem")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="routinechecks", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner", "week_start"], name="routines_ro_owner__03c2b4_idx"),
                    models.Index(fields=["owner", "item", "week_start"], name="routines_ro_owner__9a7d6f_idx"),
                ],
                "unique_together": {("owner", "item", "week_start")},
            },
        ),
    ]
