# Generated by Django 6.0.1 on 2026-02-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_rename_projects_cu_owner__a621a0_idx_projects_cu_owner_i_f6e872_idx_and_more"),
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineitem",
            name="project",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="routine_items", to="projects.project"),
        ),
    ]
