# Generated by Django 6.0.1 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_routineitem_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routineitem",
            name="time",
        ),
        migrations.AddField(
            model_name="routineitem",
            name="time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routineitem",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
