# Generated by Django 6.0.1 on 2026-02-09 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_routineitem_time_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='routine',
            new_name='routines_ro_owner_i_a78462_idx',
            old_name='routines_ro_owner__f6a1cd_idx',
        ),
        migrations.RenameIndex(
            model_name='routinecheck',
            new_name='routines_ro_owner_i_625201_idx',
            old_name='routines_ro_owner__03c2b4_idx',
        ),
        migrations.RenameIndex(
            model_name='routinecheck',
            new_name='routines_ro_owner_i_1c7597_idx',
            old_name='routines_ro_owner__9a7d6f_idx',
        ),
        migrations.RenameIndex(
            model_name='routineitem',
            new_name='routines_ro_owner_i_119125_idx',
            old_name='routines_ro_owner__2b12d1_idx',
        ),
        migrations.RenameIndex(
            model_name='routineitem',
            new_name='routines_ro_owner_i_13cff5_idx',
            old_name='routines_ro_owner__a1a4c0_idx',
        ),
        migrations.AlterField(
            model_name='routine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routinecheck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routineitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
