# Generated by Django 6.0.1 on 2026-02-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_rename_routines_ro_owner__f6a1cd_idx_routines_ro_owner_i_a78462_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinecheck',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routineitem',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
