# Generated by Django 6.0.1 on 2026-03-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_routinecheck_data_routineitem_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='routines.routinecategory'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['owner', 'category'], name='routines_ro_owner_i_0f163a_idx'),
        ),
        migrations.AddIndex(
            model_name='routinecategory',
            index=models.Index(fields=['owner', 'is_active'], name='routines_ro_owner_i_7cf16b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routinecategory',
            unique_together={('owner', 'name')},
        ),
    ]
