# Generated by Django 6.0.1 on 2026-03-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_routinecategory_routine_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_items', to='routines.routinecategory'),
        ),
        migrations.AddIndex(
            model_name='routineitem',
            index=models.Index(fields=['owner', 'category'], name='routines_ro_owner_i_44b5b3_idx'),
        ),
    ]
