# Generated by Django 6.0.1 on 2026-01-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='common_cate_owner_i_368f34_idx',
            old_name='projects_ca_owner_i_b395e8_idx',
        ),
        migrations.AlterModelTable(
            name='category',
            table='common_category',
        ),
    ]
