# Generated by Django 6.0.1 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(default='', max_length=160),
        ),
    ]
