# Generated by Django 6.0.1 on 2026-02-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_create_customers(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Customer = apps.get_model("projects", "Customer")

    for project in Project.objects.all():
        name = (project.customer or "").strip()
        if not name:
            continue
        customer, _ = Customer.objects.get_or_create(owner_id=project.owner_id, name=name)
        project.customer_ref_id = customer.id
        project.save(update_fields=["customer_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["owner", "name"], name="projects_cu_owner__a621a0_idx")],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="customer_ref",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="projects", to="projects.customer"),
        ),
        migrations.RunPython(forward_create_customers, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="project",
            name="customer",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="customer_ref",
            new_name="customer",
        ),
    ]
