# Generated by Django 6.0.1 on 2026-02-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_customer_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projectnotes", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="projects.project")),
            ],
            options={
                "indexes": [models.Index(fields=["owner", "project", "created_at"], name="projects_pr_owner__51f0ef_idx")],
            },
        ),
    ]
