# Generated by Django 6.0.1 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectnote",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="projects/notes/%Y/%m/"),
        ),
    ]
