# Generated by Django 6.0.1 on 2026-02-08 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectnote_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='projects_cu_owner_i_f6e872_idx',
            old_name='projects_cu_owner__a621a0_idx',
        ),
        migrations.RenameIndex(
            model_name='projectnote',
            new_name='projects_pr_owner_i_b0b1df_idx',
            old_name='projects_pr_owner__51f0ef_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectnote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
