# Generated by Django 6.0.1 on 2026-03-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_hero_actions_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("in_progress", "In progress"), ("blocked", "Blocked"), ("done", "Done")], default="planned", max_length=20)),
                ("priority", models.CharField(choices=[("low", "Bassa"), ("medium", "Media"), ("high", "Alta"), ("critical", "Critica")], default="medium", max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completion_percent", models.PositiveSmallIntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subprojects", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subprojects", to="projects.project")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner", "project", "status"], name="projects_sub_owner_i_774818_idx"),
                    models.Index(fields=["owner", "project", "is_archived"], name="projects_sub_owner_i_562f9e_idx"),
                ],
                "unique_together": {("owner", "project", "title")},
            },
        ),
        migrations.CreateModel(
            name="SubProjectActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("todo", "Da fare"), ("in_progress", "In corso"), ("blocked", "Bloccata"), ("done", "Completata")], default="todo", max_length=20)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subprojectactivitys", to=settings.AUTH_USER_MODEL)),
                ("subproject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="projects.subproject")),
            ],
            options={
                "ordering": ["ordering", "id"],
                "indexes": [
                    models.Index(fields=["owner", "subproject", "status"], name="projects_sub_owner_i_4ec3ec_idx"),
                    models.Index(fields=["owner", "subproject", "ordering"], name="projects_sub_owner_i_d130e8_idx"),
                ],
            },
        ),
    ]
