# Generated by Django 6.0.1 on 2026-04-29 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projectnote_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subproject',
            new_name='projects_su_owner_i_785c2e_idx',
            old_name='projects_sub_owner_i_774818_idx',
        ),
        migrations.RenameIndex(
            model_name='subproject',
            new_name='projects_su_owner_i_a52de4_idx',
            old_name='projects_sub_owner_i_562f9e_idx',
        ),
        migrations.RenameIndex(
            model_name='subprojectactivity',
            new_name='projects_su_owner_i_c80651_idx',
            old_name='projects_sub_owner_i_4ec3ec_idx',
        ),
        migrations.RenameIndex(
            model_name='subprojectactivity',
            new_name='projects_su_owner_i_1070fb_idx',
            old_name='projects_sub_owner_i_d130e8_idx',
        ),
        migrations.AlterField(
            model_name='subproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subprojectactivity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
