# Generated by Django 6.0.1 on 2026-05-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_projects_sub_owner_i_774818_idx_projects_su_owner_i_785c2e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
