# Generated by Django 6.0.1 on 2026-03-23 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_davteam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='davcalendargrant',
            new_name='core_davcal_owner_i_e922b1_idx',
            old_name='core_davcal_owner_i_f6be42_idx',
        ),
        migrations.RenameIndex(
            model_name='davexternalaccount',
            new_name='core_davext_owner_i_d81092_idx',
            old_name='core_davext_owner_i_3ba4e3_idx',
        ),
        migrations.RenameIndex(
            model_name='davmanagedcalendar',
            new_name='core_davman_owner_i_404f54_idx',
            old_name='core_davman_owner_i_084edd_idx',
        ),
        migrations.RenameIndex(
            model_name='davteam',
            new_name='core_davtea_owner_i_f4b67c_idx',
            old_name='core_davtea_owner_i_460f26_idx',
        ),
        migrations.AlterField(
            model_name='davteam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
