# Generated by Django 6.0.1 on 2026-03-05 21:42

from django.db import migrations, models


def forward_set_thread_kind(apps, schema_editor):
    ArchibaldThread = apps.get_model("archibald", "ArchibaldThread")
    ArchibaldThread.objects.filter(is_active=False).update(kind="TEMPORARY")
    ArchibaldThread.objects.filter(is_active=True).update(kind="DIARY")


class Migration(migrations.Migration):

    dependencies = [
        ('archibald', '0003_archibaldmessage_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='archibaldthread',
            name='kind',
            field=models.CharField(choices=[('DIARY', 'Diario'), ('TEMPORARY', 'Temporanea')], default='DIARY', max_length=12),
        ),
        migrations.RunPython(forward_set_thread_kind, reverse_code=migrations.RunPython.noop),
    ]
