# Generated by Django 6.0.1 on 2026-03-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archibald", "0004_archibaldthread_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="archibaldmessage",
            name="openai_response_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="archibaldthread",
            name="openai_conversation_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="archibaldthread",
            name="openai_last_response_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="archibaldthread",
            name="openai_model",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
