# Generated by Django 6.0.1 on 2026-03-14 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('source_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('source_sender', models.EmailField(blank=True, max_length=254)),
                ('source_subject', models.CharField(blank=True, max_length=255)),
                ('source_message_id', models.CharField(blank=True, max_length=255)),
                ('source_action', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'is_archived', 'created_at'], name='memory_stoc_owner_i_dadf34_idx'), models.Index(fields=['owner', 'source_message_id'], name='memory_stoc_owner_i_1bc1a3_idx'), models.Index(fields=['owner', 'updated_at'], name='memory_stoc_owner_i_7540c4_idx')],
            },
        ),
    ]
