# Generated by Django 6.0.1 on 2026-04-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorystockitem',
            name='item_type',
            field=models.CharField(choices=[('generic', 'Generico'), ('link', 'Link'), ('note', 'Nota'), ('document', 'Documento'), ('image', 'Immagine')], db_index=True, default='generic', max_length=20),
        ),
    ]
