# Generated by Django 6.0.1 on 2026-01-30 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CUSTOM', 'Custom')], default='UPDATE', max_length=10)),
                ('app_label', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debug_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='workbench_d_created_187ef0_idx'), models.Index(fields=['app_label', 'model_name', 'object_id'], name='workbench_d_app_lab_e0cdd4_idx')],
            },
        ),
    ]
