# Generated by Django 6.0.1 on 2026-01-30 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbenchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('IMPORT', 'Import'), ('REPORT', 'Report'), ('DEBUG', 'Debug')], default='DEBUG', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='OPEN', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status'], name='workbench_w_owner_i_d9d35e_idx'), models.Index(fields=['owner', 'kind'], name='workbench_w_owner_i_d23cb6_idx')],
            },
        ),
    ]
