# Generated by Django 6.0.1 on 2026-02-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_project_hero_actions_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('ACTIVITY', 'Attivita'), ('REMINDER', 'Reminder')], default='ACTIVITY', max_length=10)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Pianificata'), ('DONE', 'Completata')], default='PLANNED', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'due_date'], name='agenda_agen_owner_i_107928_idx'), models.Index(fields=['owner', 'item_type'], name='agenda_agen_owner_i_e17e41_idx'), models.Index(fields=['owner', 'status'], name='agenda_agen_owner_i_947b16_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'work_date'], name='agenda_work_owner_i_01505e_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'work_date'), name='agenda_one_worklog_per_day')],
            },
        ),
    ]
