# Generated by Django 6.0.1 on 2026-02-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
