# Generated by Django 6.0.1 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_worklog_time_end_worklog_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='lunch_break_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
