# Generated by Django 6.0.1 on 2026-03-14 21:40

import archibald_mail.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchibaldMailboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inbox_address', models.EmailField(default=archibald_mail.models.default_inbox_address, max_length=254)),
                ('timezone_name', models.CharField(default=archibald_mail.models.default_timezone_name, max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('auto_reply_subject_prefix', models.CharField(default='Re:', max_length=24)),
                ('auto_reply_signature', models.TextField(blank=True)),
                ('allowed_sender_regex', models.CharField(blank=True, max_length=180)),
                ('imap_host', models.CharField(blank=True, max_length=120)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_username', models.CharField(blank=True, max_length=180)),
                ('imap_password', models.CharField(blank=True, max_length=255)),
                ('imap_mailbox', models.CharField(default='INBOX', max_length=80)),
                ('smtp_host', models.CharField(blank=True, max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_username', models.CharField(blank=True, max_length=180)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_reply_to', models.EmailField(blank=True, max_length=254)),
                ('max_inbox_emails_per_run', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('notification_recipient', models.EmailField(blank=True, max_length=254)),
                ('notification_hour', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('notification_minute', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('notification_days_ahead', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('notification_include_tasks', models.BooleanField(default=True)),
                ('notification_include_planner', models.BooleanField(default=True)),
                ('notification_include_subscriptions', models.BooleanField(default=True)),
                ('notification_include_routines', models.BooleanField(default=True)),
                ('latest_poll_at', models.DateTimeField(blank=True, null=True)),
                ('latest_poll_status', models.CharField(blank=True, max_length=32)),
                ('latest_poll_error', models.TextField(blank=True)),
                ('last_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchibaldEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('NOTIFICATION', 'Notification'), ('TEST', 'Test')], max_length=16)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('REPLIED', 'Replied'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=16)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('external_ref', models.CharField(blank=True, max_length=120)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('ai_response_text', models.TextField(blank=True)),
                ('raw_headers', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='archibald_mail.archibaldemailmessage')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archibald_mail.archibaldmailboxconfig')),
            ],
        ),
        migrations.AddIndex(
            model_name='archibaldmailboxconfig',
            index=models.Index(fields=['owner', 'is_enabled'], name='archibald_m_owner_i_e98410_idx'),
        ),
        migrations.AddIndex(
            model_name='archibaldmailboxconfig',
            index=models.Index(fields=['owner', 'notifications_enabled'], name='archibald_m_owner_i_a65a16_idx'),
        ),
        migrations.AddConstraint(
            model_name='archibaldmailboxconfig',
            constraint=models.UniqueConstraint(fields=('owner',), name='archibald_mail_config_owner_unique'),
        ),
        migrations.AddIndex(
            model_name='archibaldemailmessage',
            index=models.Index(fields=['owner', 'config', 'direction', 'created_at'], name='archibald_m_owner_i_07778d_idx'),
        ),
        migrations.AddIndex(
            model_name='archibaldemailmessage',
            index=models.Index(fields=['owner', 'message_id'], name='archibald_m_owner_i_31f9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='archibaldemailmessage',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='archibald_m_owner_i_f18071_idx'),
        ),
    ]
