# Generated by Django 6.0.1 on 2026-03-15 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archibald_mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchibaldEmailFlagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=60)),
                ('flag_token', models.CharField(max_length=32)),
                ('action_key', models.CharField(choices=[('memory_stock.save', 'Memory Stock'), ('todo.capture', 'Todo (fallback Memory Stock)'), ('transaction.capture', 'Transaction (fallback Memory Stock)')], default='memory_stock.save', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'is_active', 'flag_token'], name='archibald_m_owner_i_f57016_idx'), models.Index(fields=['owner', 'action_key', 'is_active'], name='archibald_m_owner_i_b9ba61_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'flag_token'), name='archibald_mail_flag_owner_token_uniq')],
            },
        ),
    ]
