# Generated by Django 6.0.1 on 2026-03-15 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archibald_mail', '0002_archibaldemailflagrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archibaldemailmessage',
            name='classification_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='archibaldemailmessage',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='archibaldemailmessage',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('IGNORED', 'Ignored')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='archibaldemailmessage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archibaldemailmessage',
            name='selected_action_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='archibaldemailflagrule',
            name='action_key',
            field=models.CharField(choices=[('memory_stock.save', 'Memory Stock'), ('todo.capture', 'Todo (fallback Memory Stock)'), ('transaction.capture', 'Transaction (fallback Memory Stock)'), ('reminder.capture', 'Reminder (fallback Memory Stock)')], default='memory_stock.save', max_length=64),
        ),
        migrations.AddIndex(
            model_name='archibaldemailmessage',
            index=models.Index(fields=['owner', 'direction', 'review_status', 'created_at'], name='archibald_m_owner_i_b78caf_idx'),
        ),
    ]
