# Generated by Django 6.0.1 on 2026-03-15 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archibald_mail', '0003_archibaldemailmessage_classification_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchibaldInboundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archibaldemailmessage',
            name='classification_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='archibald_mail.archibaldinboundcategory'),
        ),
        migrations.AddIndex(
            model_name='archibaldinboundcategory',
            index=models.Index(fields=['owner', 'is_active', 'label'], name='archibald_m_owner_i_fc840e_idx'),
        ),
        migrations.AddConstraint(
            model_name='archibaldinboundcategory',
            constraint=models.UniqueConstraint(fields=('owner', 'label'), name='archibald_mail_inbound_category_owner_label_uniq'),
        ),
    ]
