# Generated by Django 6.0.1 on 2026-03-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archibald_mail', '0004_archibaldinboundcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archibaldmailboxconfig',
            name='notification_include_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
