# Generated by Django 6.0.1 on 2026-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archibald_mail", "0005_archibaldmailboxconfig_notification_include_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archibaldemailflagrule",
            name="action_key",
            field=models.CharField(
                choices=[
                    ("memory_stock.save", "Memory Stock"),
                    ("todo.capture", "Todo (fallback Memory Stock)"),
                    ("transaction.capture", "Transaction (fallback Memory Stock)"),
                    ("reminder.capture", "Reminder (fallback Memory Stock)"),
                    ("archi.reply", "Archibald reply immediata"),
                ],
                default="memory_stock.save",
                max_length=64,
            ),
        ),
    ]
