# Generated by Django 6.0.1 on 2026-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archibald_mail', '0006_alter_archibaldemailflagrule_action_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archibaldemailflagrule',
            name='action_key',
            field=models.CharField(choices=[('memory_stock.save', 'Memory Stock'), ('todo.capture', 'Todo (fallback Memory Stock)'), ('transaction.capture', 'Transaction (fallback Memory Stock)'), ('reminder.capture', 'Reminder (fallback Memory Stock)'), ('archi.reply', 'Archibald reply immediata'), ('worklog.capture_am', 'Worklog mattina (Agenda)'), ('worklog.capture_pm', 'Worklog pomeriggio (Agenda)')], default='memory_stock.save', max_length=64),
        ),
    ]
