# Generated by Django 6.0.1 on 2026-05-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archibald_mail', '0007_alter_archibaldemailflagrule_action_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='archibaldmailboxconfig',
            name='notification_include_todos',
            field=models.BooleanField(default=True),
        ),
    ]
