# Generated by Django 6.0.1 on 2026-02-27 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_hero_actions_config'),
        ('todo', '0005_task_due_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_tasks', to='projects.category'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'category'], name='todo_task_owner_i_0a9838_idx'),
        ),
    ]
