# Generated by Django 6.0.1 on 2026-02-18 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, choices=[('TECNOLOGIA', 'Tecnologia'), ('SALUTE', 'Salute'), ('SPORT', 'Sport'), ('INTRATTENIMENTO', 'Intrattenimento')], max_length=15)),
                ('importance', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'created_at'], name='link_storag_owner_i_1f88b7_idx')],
            },
        ),
    ]
