# Generated by Django 6.0.1 on 2026-04-30 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_storage', '0001_initial'),
        ('memory_stock', '0002_memorystockitem_item_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description_extracted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='link',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='link',
            name='memory_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_specialization', to='memory_stock.memorystockitem'),
        ),
        migrations.AddField(
            model_name='link',
            name='title_extracted',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(blank=True, choices=[('TECNOLOGIA', 'Tecnologia'), ('SALUTE', 'Salute'), ('SPORT', 'Sport'), ('INTRATTENIMENTO', 'Intrattenimento'), ('LAVORO', 'Lavoro'), ('STUDIO', 'Studio'), ('ALTRI', 'Altri')], max_length=15),
        ),
        migrations.AlterField(
            model_name='link',
            name='importance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['owner', 'category'], name='link_storag_owner_i_af7ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['owner', 'importance'], name='link_storag_owner_i_679b2f_idx'),
        ),
    ]
