# Generated by Django 6.0.1 on 2026-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='item_type',
            field=models.CharField(choices=[('TASK', 'Task da completare'), ('REMINDER', 'Reminder')], default='TASK', max_length=10),
        ),
    ]
