# Generated by Django 6.0.1 on 2026-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item_type',
            field=models.CharField(choices=[('TASK', 'Task da completare'), ('REMINDER', 'Reminder'), ('APPOINTMENT', 'Appuntamento')], default='TASK', max_length=12),
        ),
    ]
