from django.urls import include, path

from . import views

urlpatterns = [
    path("api/mobile/auth/login", views.mobile_auth_login, name="mobile-auth-login"),
    path("api/mobile/auth/refresh", views.mobile_auth_refresh, name="mobile-auth-refresh"),
    path("api/mobile/auth/logout", views.mobile_auth_logout, name="mobile-auth-logout"),
    path("api/mobile/dashboard", views.mobile_dashboard, name="mobile-dashboard"),
    path("api/mobile/todos", views.mobile_todos, name="mobile-todos"),
    path("api/mobile/todos/check", views.mobile_todos_check, name="mobile-todos-check"),
    path("api/mobile/todos/items/create", views.mobile_todos_item_create, name="mobile-todos-item-create"),
    path("api/mobile/todos/items/update", views.mobile_todos_item_update, name="mobile-todos-item-update"),
    path("api/mobile/todos/items/delete", views.mobile_todos_item_delete, name="mobile-todos-item-delete"),
    path("api/todos", views.api_todos, name="api-todos"),
    path("api/todos/check", views.api_todos_check, name="api-todos-check"),
    path("api/todos/items/create", views.api_todos_item_create, name="api-todos-item-create"),
    path("api/todos/items/update", views.api_todos_item_update, name="api-todos-item-update"),
    path("api/todos/items/delete", views.api_todos_item_delete, name="api-todos-item-delete"),
    path("api/projects", views.api_projects, name="api-projects"),
    path("api/mobile/projects", views.mobile_projects, name="mobile-projects"),
    path("api/agenda", views.api_agenda, name="api-agenda"),
    path("api/mobile/agenda", views.mobile_agenda, name="mobile-agenda"),
    path('', views.dashboard, name='core-dashboard'),
    path('dashboard/widgets', views.dashboard_widgets, name='core-dashboard-widgets'),
    path('dashboard/preferences', views.dashboard_preferences, name='core-dashboard-preferences'),
    path('dashboard/snapshot', views.dashboard_snapshot, name='core-dashboard-snapshot'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/login/', views.AccountLoginView.as_view(), name='login'),
    path('accounts/password_change/', views.AccountPasswordChangeView.as_view(), name='password_change'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/dav/', views.dav_management, name='dav-management'),
    path('profile/nav/', views.nav_settings, name='nav-settings'),
    path('calendar/events', views.calendar_events, name='core-calendar-events'),
    path('core/accounts/', views.accounts, name='core-accounts'),
    path('core/accounts/add', views.add_account, name='core-accounts-add'),
    path('core/accounts/remove', views.remove_account, name='core-accounts-remove'),
    path('core/accounts/update', views.update_account, name='core-accounts-update'),
    path('core/legacy-dashboard/', views.dashboard, name='core-legacy-dashboard'),
]
