# Generated by Django 6.0.1 on 2026-05-11 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0012_rename_projects_sub_owner_i_774818_idx_projects_su_owner_i_785c2e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_lists', to='todos.todocategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lun'), (1, 'Mar'), (2, 'Mer'), (3, 'Gio'), (4, 'Ven'), (5, 'Sab'), (6, 'Dom')], default=0)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('item_type', models.CharField(choices=[('TASK', 'Task'), ('REMINDER', 'Reminder'), ('APPOINTMENT', 'Appuntamento')], default='TASK', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='OPEN', max_length=12)),
                ('is_standalone', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_items', to='todos.todocategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_items', to='projects.project')),
                ('todo_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todos.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='TodoRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='PLANNED', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='todos.todoitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='todocategory',
            index=models.Index(fields=['owner', 'is_active'], name='todos_todoc_owner_i_3baf37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='todocategory',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['owner', 'is_active'], name='todos_todol_owner_i_72789e_idx'),
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['owner', 'category'], name='todos_todol_owner_i_dd6202_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['owner', 'weekday'], name='todos_todoi_owner_i_de0d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['owner', 'todo_list', 'weekday'], name='todos_todoi_owner_i_db5c57_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['owner', 'category'], name='todos_todoi_owner_i_870bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['owner', 'due_date'], name='todos_todoi_owner_i_50a4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['owner', 'item_type'], name='todos_todoi_owner_i_0237a4_idx'),
        ),
        migrations.AddIndex(
            model_name='todorecurrence',
            index=models.Index(fields=['owner', 'week_start'], name='todos_todor_owner_i_1be49c_idx'),
        ),
        migrations.AddIndex(
            model_name='todorecurrence',
            index=models.Index(fields=['owner', 'todo_item', 'week_start'], name='todos_todor_owner_i_ff114e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='todorecurrence',
            unique_together={('owner', 'todo_item', 'week_start')},
        ),
    ]
