# Generated by Django 6.0.1 on 2026-01-31 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        ('subscriptions', '0002_alter_payee_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_type', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense'), ('XFER', 'Transfer')], max_length=4)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscriptions.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='projects.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.payee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='projects.project')),
                ('source_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='subscriptions.subscription')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='subscriptions.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'date'], name='transaction_owner_i_2f580e_idx'), models.Index(fields=['owner', 'tx_type', 'date'], name='transaction_owner_i_718db9_idx'), models.Index(fields=['owner', 'project', 'date'], name='transaction_owner_i_0ee5f2_idx')],
            },
        ),
    ]
