# Generated by Django 6.0.1 on 2026-02-01 00:00

from django.db import migrations


def migrate_income_sources(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")
    IncomeSource = apps.get_model("income", "IncomeSource")

    db_alias = schema_editor.connection.alias
    transactions = (
        Transaction.objects.using(db_alias)
        .filter(tx_type="IN", payee__isnull=False, income_source__isnull=True)
        .select_related("payee")
    )
    for tx in transactions:
        if not tx.payee_id:
            continue
        source, _ = IncomeSource.objects.using(db_alias).get_or_create(
            owner_id=tx.owner_id,
            name=tx.payee.name,
            defaults={"website": getattr(tx.payee, "website", "") or ""},
        )
        Transaction.objects.using(db_alias).filter(id=tx.id).update(income_source_id=source.id)


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
        ("transactions", "0002_transaction_income_source"),
    ]

    operations = [
        migrations.RunPython(migrate_income_sources, migrations.RunPython.noop),
    ]
