# Generated by Django 6.0.1 on 2026-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_migrate_income_source_from_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='transactions/attachments/%Y/%m/'),
        ),
    ]
