# Generated by Django 6.0.1 on 2026-04-29 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_hub', '0012_account_subscription_subscriptionoccurrence_and_more'),
        ('transactions', '0005_alter_transaction_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance_hub.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_hub.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='income_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance_hub.incomesource'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='finance_hub.subscription'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='finance_hub.tag'),
        ),
    ]
