# Generated by Django 6.0.1 on 2026-05-11 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0013_project_enabled_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('threads', 'Threads'), ('other', 'Altro')], default='instagram', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('handle', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_channels', to='projects.project')),
            ],
            options={
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('scheduled', 'Programmato'), ('published', 'Pubblicato'), ('archived', 'Archiviato')], default='draft', max_length=20)),
                ('content', models.TextField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('engagement_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_media.socialchannel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='projects.project')),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialchannel',
            index=models.Index(fields=['owner', 'project', 'is_active'], name='social_medi_owner_i_81e135_idx'),
        ),
        migrations.AddIndex(
            model_name='socialchannel',
            index=models.Index(fields=['owner', 'project', 'platform'], name='social_medi_owner_i_2fec49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialchannel',
            unique_together={('owner', 'project', 'platform', 'name')},
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['owner', 'project', 'status', 'scheduled_at'], name='social_medi_owner_i_740fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['owner', 'project', 'status', 'published_at'], name='social_medi_owner_i_bd1fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['owner', 'project', 'created_at'], name='social_medi_owner_i_9d76aa_idx'),
        ),
    ]
