# Generated by Django 6.0.1 on 2026-05-11 21:42

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=social_media.models.social_post_media_upload_to),
        ),
    ]
