"""
Django settings for mio_master project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-=8wipcv7k4(#y*s*mgk&lre$vb5#2@c(j=nuwb_q^+^z-=)##4",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes", "on"}

_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "archibald.onrender.com"]

_csrf_trusted_origins = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_origins.split(",") if o.strip()]

_mobile_api_allowed_origins = os.getenv("MOBILE_API_ALLOWED_ORIGINS", "")
MOBILE_API_ALLOWED_ORIGINS = [o.strip() for o in _mobile_api_allowed_origins.split(",") if o.strip()]
if not MOBILE_API_ALLOWED_ORIGINS:
    MOBILE_API_ALLOWED_ORIGINS = [
        "http://localhost",
        "https://localhost",
        "capacitor://localhost",
        "ionic://localhost",
    ]

MOBILE_API_ACCESS_TTL_SECONDS = int(os.getenv("MOBILE_API_ACCESS_TTL_SECONDS", "900"))
MOBILE_API_REFRESH_TTL_DAYS = int(os.getenv("MOBILE_API_REFRESH_TTL_DAYS", "14"))
CALDAV_ENABLED = os.getenv("CALDAV_ENABLED", "false").lower() in {"1", "true", "yes", "on"}
CALDAV_BASE_URL = os.getenv("CALDAV_BASE_URL", "").strip()
CALDAV_SERVICE_USERNAME = os.getenv("CALDAV_SERVICE_USERNAME", "").strip()
CALDAV_SERVICE_PASSWORD = os.getenv("CALDAV_SERVICE_PASSWORD", "").strip()
CALDAV_LOGIN_DOMAIN = os.getenv("CALDAV_LOGIN_DOMAIN", "").strip()
CALDAV_DEFAULT_TEAM_COLLECTION = os.getenv("CALDAV_DEFAULT_TEAM_COLLECTION", "team/progetto-generale").strip()
RADICALE_USERS_FILE = os.getenv("RADICALE_USERS_FILE", str(BASE_DIR / "runtime" / "radicale" / "users")).strip()
RADICALE_USERS_LOCK_FILE = os.getenv("RADICALE_USERS_LOCK_FILE", "").strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'income',
    'outcome',
    'projects',
    'subscriptions',
    'todo',
    'agenda',
    'workbench',
    'transactions',
    'planner',
    'routines',
    'archibald',
    'archibald_mail',
    'memory_stock',
    'ai_lab',
    'vault',
    'link_storage',
    'finance_hub',
    'contacts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "core.mobile_api.MobileApiCorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "workbench.middleware.DebugChangeLogMiddleware",
]

ROOT_URLCONF = 'mio_master.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.hero_actions_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'mio_master.wsgi.application'


database_url = os.getenv("DATABASE_URL")
db_ssl_require = os.getenv("DJANGO_DB_SSL_REQUIRE", "false").lower() in {"1", "true", "yes", "on"}
if not database_url:
    raise ImproperlyConfigured(
        "DATABASE_URL is required. This project uses PostgreSQL only (Docker/local/VPS)."
    )

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": dj_database_url.parse(
        database_url,
        conn_max_age=600,
        ssl_require=db_ssl_require,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Auth redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
