# Generated by Django 6.0.1 on 2026-01-30 21:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('BANK', 'Bank'), ('CARD', 'Card'), ('CASH', 'Cash'), ('INVEST', 'Investment'), ('OTHER', 'Other')], default='BANK', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('website', models.URLField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('interval_unit', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='MONTH', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10)),
                ('autopay', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='projects.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.payee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='projects.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='subscriptions', to='subscriptions.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_type', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense'), ('XFER', 'Transfer')], max_length=4)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscriptions.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='projects.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.payee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='projects.project')),
                ('source_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='subscriptions.subscription')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='subscriptions.tag')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('PLANNED', 'Planned'), ('PAID', 'Paid'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PLANNED', max_length=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='subscriptions.subscription')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_occurrence', to='subscriptions.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'is_active'], name='subscriptio_owner_i_cdb99f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='payee',
            index=models.Index(fields=['owner', 'name'], name='subscriptio_owner_i_0e3d8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payee',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner', 'name'], name='subscriptio_owner_i_48f4c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'status', 'next_due_date'], name='subscriptio_owner_i_519c89_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'project', 'status'], name='subscriptio_owner_i_aa398b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'date'], name='subscriptio_owner_i_f36220_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'tx_type', 'date'], name='subscriptio_owner_i_93282d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'project', 'date'], name='subscriptio_owner_i_dae629_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionoccurrence',
            index=models.Index(fields=['owner', 'due_date', 'state'], name='subscriptio_owner_i_80fce5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionoccurrence',
            index=models.Index(fields=['owner', 'subscription', 'due_date'], name='subscriptio_owner_i_ce9f1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionoccurrence',
            unique_together={('subscription', 'due_date')},
        ),
    ]
