# Generated by Django 6.0.1 on 2026-01-31 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payee',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='payee',
            name='subscriptio_owner_i_0e3d8e_idx',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.payee'),
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='subscriptio_owner_i_f36220_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='subscriptio_owner_i_93282d_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='subscriptio_owner_i_dae629_idx',
        ),
    ]
