# Generated by Django 6.0.1 on 2026-01-31 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_payee_unique_together_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoccurrence',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_occurrence', to='transactions.transaction'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='project',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_subscription',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Payee',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
