# Generated by Django 6.0.1 on 2026-01-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionoccurrence_transaction_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='core_accoun_owner_i_94d652_idx',
            old_name='subscriptio_owner_i_cdb99f_idx',
        ),
        migrations.AlterModelTable(
            name='account',
            table='core_accounts',
        ),
    ]
