# Generated by Django 6.0.1 on 2026-01-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_subscriptio_owner_i_cdb99f_idx_core_accoun_owner_i_94d652_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='common_currency',
        ),
    ]
