# Generated by Django 6.0.1 on 2026-04-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_hub', '0012_account_subscription_subscriptionoccurrence_and_more'),
        ('subscriptions', '0005_alter_currency_table'),
        ('transactions', '0006_alter_transaction_account_alter_transaction_currency_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='account',
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name='account',
                    name='core_accoun_owner_i_94d652_idx',
                ),
                migrations.AlterUniqueTogether(
                    name='subscription',
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name='subscription',
                    name='subscriptio_owner_i_519c89_idx',
                ),
                migrations.RemoveIndex(
                    model_name='subscription',
                    name='subscriptio_owner_i_aa398b_idx',
                ),
                migrations.AlterUniqueTogether(
                    name='subscriptionoccurrence',
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name='subscriptionoccurrence',
                    name='subscriptio_owner_i_80fce5_idx',
                ),
                migrations.RemoveIndex(
                    model_name='subscriptionoccurrence',
                    name='subscriptio_owner_i_ce9f1b_idx',
                ),
                migrations.AlterUniqueTogether(
                    name='tag',
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name='tag',
                    name='subscriptio_owner_i_48f4c1_idx',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='account',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='category',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='owner',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='payee',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='subscription',
                    name='tags',
                ),
                migrations.RemoveField(
                    model_name='subscriptionoccurrence',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='subscriptionoccurrence',
                    name='owner',
                ),
                migrations.RemoveField(
                    model_name='subscriptionoccurrence',
                    name='subscription',
                ),
                migrations.RemoveField(
                    model_name='subscriptionoccurrence',
                    name='transaction',
                ),
                migrations.RemoveField(
                    model_name='tag',
                    name='owner',
                ),
                migrations.DeleteModel(
                    name='Account',
                ),
                migrations.DeleteModel(
                    name='Currency',
                ),
                migrations.DeleteModel(
                    name='Subscription',
                ),
                migrations.DeleteModel(
                    name='SubscriptionOccurrence',
                ),
                migrations.DeleteModel(
                    name='Tag',
                ),
            ],
            database_operations=[],
        ),
    ]
