# Generated by Django 6.0.1 on 2026-02-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('area', models.CharField(choices=[('FOUNDATIONS', 'Fondamentali'), ('PROMPTING', 'Prompting'), ('EMBEDDINGS', 'Embeddings'), ('RAG', 'RAG'), ('VECTOR_DB', 'Vector DB'), ('EXPERIMENT', 'Esperimento libero')], default='FOUNDATIONS', max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'Da studiare'), ('LEARNING', 'In studio'), ('TESTING', 'In test'), ('APPLIED', 'Applicato')], default='TODO', max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('next_step', models.CharField(blank=True, max_length=220)),
                ('resource_url', models.URLField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'area', 'status'], name='ai_lab_labe_owner_i_d72dcc_idx'), models.Index(fields=['owner', 'updated_at'], name='ai_lab_labe_owner_i_69ffce_idx')],
            },
        ),
    ]
