# Generated by Django 6.0.1 on 2026-02-20 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchibaldPersonaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset', models.CharField(choices=[('OPERATIVE', 'Operativo diretto'), ('BALANCED', 'Bilanciato'), ('CLASSIC', 'Magiordomo classico')], default='BALANCED', max_length=12)),
                ('verbosity', models.CharField(choices=[('SHORT', 'Breve'), ('MEDIUM', 'Media'), ('LONG', 'Dettagliata')], default='MEDIUM', max_length=10)),
                ('challenge_level', models.CharField(choices=[('LOW', 'Delicato'), ('NORMAL', 'Normale'), ('HIGH', 'Sfida attiva')], default='NORMAL', max_length=10)),
                ('action_mode', models.CharField(choices=[('WHEN_USEFUL', 'Azioni pratiche quando utili'), ('ALWAYS', 'Chiudi sempre con azioni pratiche'), ('NEVER', 'Niente lista azioni finali')], default='WHEN_USEFUL', max_length=12)),
                ('avoid_pandering', models.BooleanField(default=True)),
                ('include_reasoning', models.BooleanField(default=True)),
                ('custom_instructions', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'updated_at'], name='ai_lab_arch_owner_i_00bbaf_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner',), name='ai_lab_archibald_persona_owner_unique')],
            },
        ),
    ]
