# Generated by Django 6.0.1 on 2026-02-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0002_archibaldpersonaconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_accountability_nudge',
            field=models.BooleanField(default=True, help_text='Introduce responsabilizzazione gentile e follow-up pratico.', verbose_name='Nudge accountability'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_assertive_boundaries',
            field=models.BooleanField(default=True, help_text='Protegge priorita e limiti, evitando dispersione.', verbose_name='Confini assertivi'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_bias_check',
            field=models.BooleanField(default=True, help_text='Evidenzia catastrofismo, tutto-o-nulla e inferenze fragili.', verbose_name='Controllo bias'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_cognitive_reframe',
            field=models.BooleanField(default=True, help_text='Trasforma formulazioni bloccanti in letture piu utili.', verbose_name='Riformulazione cognitiva'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_decision_simplify',
            field=models.BooleanField(default=True, help_text='Riduce il carico decisionale con opzioni nette e criteri chiari.', verbose_name='Semplificazione decisionale'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_micro_actions',
            field=models.BooleanField(default=True, help_text='Propone passi piccoli e concreti per sbloccarsi subito.', verbose_name='Micro-azioni immediate'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_non_judgmental_tone',
            field=models.BooleanField(default=True, help_text='Mantiene linguaggio rispettoso evitando colpevolizzazione.', verbose_name='Tono non giudicante'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_self_efficacy',
            field=models.BooleanField(default=True, help_text="Rinforza senso di competenza e capacita di azione dell'utente.", verbose_name='Rinforzo autoefficacia'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_socratic_questions',
            field=models.BooleanField(default=False, help_text='Fa domande guida per aumentare consapevolezza e chiarezza.', verbose_name='Domande socratiche'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='psych_validate_emotions',
            field=models.BooleanField(default=True, help_text='Riconosce e legittima lo stato emotivo prima della soluzione.', verbose_name='Validazione emotiva'),
        ),
    ]
