# Generated by Django 6.0.1 on 2026-02-20 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0003_archibaldpersonaconfig_psych_accountability_nudge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchibaldInstructionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('instructions_text', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'name'], name='ai_lab_arch_owner_i_95db7f_idx'), models.Index(fields=['owner', 'updated_at'], name='ai_lab_arch_owner_i_471907_idx')],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
