# Generated by Django 6.0.1 on 2026-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0004_archibaldinstructionstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='bias_all_or_nothing',
            field=models.BooleanField(default=True, help_text='Riconosce valutazioni in bianco/nero prive di gradazioni.', verbose_name='Pensiero tutto-o-nulla'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='bias_catastrophizing',
            field=models.BooleanField(default=True, help_text='Individua scenari estremi non supportati dai dati.', verbose_name='Catastrofismo'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='bias_confirmation_bias',
            field=models.BooleanField(default=True, help_text='Evidenzia selezione parziale delle prove a favore della tesi iniziale.', verbose_name='Bias di conferma'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='bias_mind_reading',
            field=models.BooleanField(default=True, help_text='Segnala assunzioni sulle intenzioni altrui senza evidenze.', verbose_name='Lettura del pensiero'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='bias_negative_filtering',
            field=models.BooleanField(default=True, help_text='Contrasta il focus esclusivo sugli aspetti negativi.', verbose_name='Filtro negativo'),
        ),
        migrations.AddField(
            model_name='archibaldpersonaconfig',
            name='bias_overgeneralization',
            field=models.BooleanField(default=True, help_text='Evita conclusioni globali basate su pochi episodi.', verbose_name='Sovrageneralizzazione'),
        ),
    ]
