# Generated by Django 6.0.1 on 2026-04-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0006_alter_archibaldpersonaconfig_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archibaldpersonaconfig',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='labentry',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ArchibaldInstructionState',
        ),
        migrations.DeleteModel(
            name='ArchibaldPersonaConfig',
        ),
        migrations.DeleteModel(
            name='LabEntry',
        ),
    ]
