# Generated by Django 6.0.1 on 2026-02-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incomesource',
            new_name='income_inco_owner_i_7b6184_idx',
            old_name='income_incomesource_owner_i_7fa3f9_idx',
        ),
    ]
