# Generated by Django 6.0.1 on 2026-04-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_rename_income_incomesource_owner_i_7fa3f9_idx_income_inco_owner_i_7b6184_idx'),
        ('transactions', '0006_alter_transaction_account_alter_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomesource',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='incomesource',
            name='income_inco_owner_i_7b6184_idx',
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
    ]
