# Generated by Django 6.0.1 on 2026-01-31 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('projects', '0002_rename_projects_ca_owner_i_b395e8_idx_common_cate_owner_i_368f34_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planneritem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_items', to='projects.category'),
        ),
        migrations.AddField(
            model_name='planneritem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_items', to='projects.project'),
        ),
    ]
